---
- name: This is an ansible playbook roles
  hosts: prod
  become: yes
  gather_facts: no

  roles:

#   - /home/ansible/ansible-roles/upgrade-packages
    - firewalld/
    - tomcat/
#   - /home/ansible/ansible-roles/terraform
#   - /home/ansible/ansible-roles/jenkins
#   - /home/ansible/ansible-roles/maven
